### ISSUE TITLE
Linking Bulma from a CDN rather than download.

### ISSUE THREAD

**Issue by atkinsta** [smhodgesii/ProjectOne#8]
I noticed that we have Bulma linked to our project with a downloaded .css file. Would it be cleaner and easier to use cdnjs.com for Bulma? See the following link,

https://cdnjs.com/libraries/bulma

**Comment by smhodgesii** [comment]
I edited Bulma's CSS with SASS, so we will be linking in our own CSS file instead of using a CDN. Bulma is also modular, so by the end of the project we will be able to significantly trim down the size of that CSS file using SASS, and it will end up being faster than using a CDN.
